#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : execnet
Version  : 1.4.1
Release  : 15
URL      : https://pypi.python.org/packages/source/e/execnet/execnet-1.4.1.tar.gz
Source0  : https://pypi.python.org/packages/source/e/execnet/execnet-1.4.1.tar.gz
Summary  : execnet: rapid multi-Python deployment
Group    : Development/Tools
License  : MIT
Requires: execnet-python
BuildRequires : apipkg
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : setuptools_scm
BuildRequires : tox
BuildRequires : virtualenv

%description
Welcome to execnet and elastic distributed computing!
Rapidly deploy tools and code to local or remote Python interpreters.

%package python
Summary: python components for the execnet package.
Group: Default

%description python
python components for the execnet package.


%prep
%setup -q -n execnet-1.4.1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1484545958
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1484545958
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
